### ISSUE TITLE
Compilation error due to PR #7

### ISSUE THREAD

**Issue by ghost** [ros2/rosbag2_bag_v2#11]
Starting from a fresh installation of eloquent i tried to build from source this plugin and I got an error caused by the method `get_relative_file_path` of `rosbag2_bag_v2_plugins/src/rosbag2_bag_v2_plugins/storage/rosbag_v2_storage.hpp` that it's still `get_relative_path` in the original interface.
Reverting back the method's name fixed the issue.

**Comment by Karsten1987** [comment]
rosbag2 has that method changed to `get_relative_file_path` in here: https://github.com/ros2/rosbag2/blob/master/rosbag2_storage/include/rosbag2_storage/storage_interfaces/base_info_interface.hpp#L41

Are you using the latest rosbag2 version of eloquent?

**Comment by ghost** [comment]
@Karsten1987 yep I had to update the rosbag2 package :sweat_smile:
