### ISSUE TITLE
CMake only logs warning when roscpp is not found

### ISSUE THREAD

**Issue by piraka9011** [ros2/rosbag2_bag_v2#13]
When CMake want's to find the `roscpp` package, it currently [only logs a warning](https://github.com/ros2/rosbag2_bag_v2/blob/842056f5bbbd9d1ed4f78d99d6c0c3755060924e/rosbag2_bag_v2_plugins/CMakeLists.txt#L30). 
Since `rosbag_v2` depends on `roscpp`, the build should fail and not skip.

**Comment by wjwwood** [comment]
I don't think we want this, because otherwise we'll have to remove this package or otherwise disable it when building without ROS 1 (a common practice).

~~If you want to change this to an error I think you should also move this package into a separate repository.~~

**Comment by wjwwood** [comment]
Oh sorry, this is already a separate repository. And it's not in the main `ros2.repos` file, so that should be ok. Sorry for the noise.
