### ISSUE TITLE
Can use rosbag2_v2 but cannot echo topic

### ISSUE THREAD

**Issue by llu0120** [ros2/rosbag2_bag_v2#35]
I'm using ROS2 dashing and ROS1 melodic on a ubuntu18.04. I successfully run the plugin, like below: 
![Selection_049](https://user-images.githubusercontent.com/41609738/93562556-3fbad780-f954-11ea-8411-d26621b07dc9.png)
However, when I try to echo the topics simultaneously like below, it appears some failure message: 
![Selection_050](https://user-images.githubusercontent.com/41609738/93562643-7264d000-f954-11ea-9e32-ef5cda506913.png)

Anyone have some idea on how to solve this? Thank you!

**Comment by emersonknapp** [comment]
Can you clarify any more information about your setup?

* Did you source ROS 1 workspace first, then ROS 2 workspace second?
* How is `/pandar` being published in this scenario? Is it a ROS 1 node publishing live, or is it via `rosbag2` playback?

**Comment by emersonknapp** [comment]
Due to no response, I will close this issue for now. If this is still a problem, please feel free to reopen with more information.
