### ISSUE TITLE
ROS Noetic is not available on Ubuntu Jammy

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosbag2_bag_v2#46]
With Rolling's recent migration to Ubuntu Jammy, the ROS Noetic dependencies for packages like the ros1_bridge and ros1_rosbag_storage_vendor which are patched into the release data since rosdep cannot handle cross-rosdistro dependencies are no longer available.

While it is possible that the ros1_bridge may be updated in the future to work with other distributions of ROS, I have proposed removing it from Rolling's release configuration for now https://github.com/ros/rosdistro/pull/32245

Since the ros1_bridge is a dependency of rosbag2_bag_v2_plugins this change will make this package un-releasable as well.

If it's possible to isolate the ROS 1 and ros1_bridge dependencies into separate packages from other plugins then the packages requiring the unavailable dependencies can be ignored at release time with a `rolling.ignored` file in the release repository.
If the only plugins currently available depend on ROS 1 I would suggest that we remove this repository from Rolling's release configuration like I've proposed for the ros1_bridge.

**Comment by emersonknapp** [comment]
It's an unfortunate situation, I think folks will want to continue to playback their ROS1 bags in ROS2. But, I don't see the development resources coming from anywhere to support that, so I suppose we must deprecate this package from Rolling for the time being.

**Comment by clalancette** [comment]
We discussed this, and this has already been disabled in Rolling.  If someone goes ahead and does the work, we can re-introduce it into Rolling, but we're going to close this issue for now.
