### ISSUE TITLE
Topic information not displayed

### ISSUE THREAD

**Issue by jeychandar** [ros2/rosbag2_bag_v2#48]
Hi. I tried converting pcap format to bag format with this tool https://github.com/Krishtof-Korda/pcap-to-bag.git. The resulted bag file does not showing the topic information. Could you please clarify me and help me out. Thanks in advance
 
![image](https://user-images.githubusercontent.com/48254471/212975599-30a246ef-6d73-4eaa-864e-d61fce221a2c.png)

**Comment by emersonknapp** [comment]
Request: In the future could you please copy-paste output, instead of providing a screenshot? It is easier to read, copy, etc that way.

Question: Which distributions are you using? For each of Ubuntu, ROS, and ROS 2

Does ROS 1's `rosbag info` show topic information for this bag? I am wondering where in the process the information is being lost. Maybe the conversion tool doesn't produce it - I'm not familiar with the tool.

I'm looking at the output there

```
ROS 1 to ROS 2 type mapping is not available for ... type 'ouster_ros/PacketMsg'. Skipping messages of this topic.
```

Maybe that has something to do with it - I see that `ouster_ros` is not a bloom-released package (meaning that you can't `apt install ros-$DISTRO-ouster-ros`). Do you have this package built in your workspaces for both for ROS and ROS 2?

**Comment by jeychandar** [comment]
Hi yes sure I'll copy paste next time, For both I'm using Linux distribution. ROS1 Noetic and ROS2 foxy debian packages.
Yes I am getting Rosbag info. I too not familiar with that tool. But I'm trying to convert pcap to bag format. For that this tool only available but it doesn't providing topic information for ros2. So far I'm using rosbag_v2 but this is new for me. I'm confused. Could you suggest me an idea to overcome this issue. It will be helpful.

**Comment by emersonknapp** [comment]
If you are using Noetic and Foxy, then it must be Ubuntu 20.04 Focal (that's what I meant by which Ubuntu distribution)

I think you just need a ROS 2 definition for the `ouster_ros/PacketMsg` type. 
https://github.com/ros-drivers/ros2_ouster_drivers has packages that provide this, you should be able to call

```
apt install ros-foxy-ouster-msgs
```

Maybe after you install that package, then the info will work correctly.

**Comment by jeychandar** [comment]
> If you are using Noetic and Foxy, then it must be Ubuntu 20.04 Focal (that's what I meant by which Ubuntu distribution)
> 
> I think you just need a ROS 2 definition for the `ouster_ros/PacketMsg` type. https://github.com/ros-drivers/ros2_ouster_drivers has packages that provide this, you should be able to call
> 
> ```
> apt install ros-foxy-ouster-msgs
> ```
> 
> Maybe after you install that package, then the info will work correctly.

Hi. I tried installing as you said but still same error.

**Comment by emersonknapp** [comment]
Yeah, I guess that makes sense.  The message type you are looking at is https://github.com/ouster-lidar/ouster-ros/blob/master/msg/PacketMsg.msg - but in this [ros2 driver messages](https://github.com/ros-drivers/ros2_ouster_drivers/tree/ros2/ouster_msgs/msg) there is only `Metadata.msg`. You might have to define this type yourself in a source patch. Perhaps you can try making a simple `ament_cmake` package in your workspace, name it `ouster_ros`, and provide  `PacketMsg.msg` in it. I think that `rosbag2_bag_v2` is going to be looking for a local ROS2 definition for `ouster_ros/PacketMsg`, so you need to provide that somehow.

Long-term, perhaps you could ask `ouster-lidar/ouster_ros` to provide a ros2-compatible port of the package. Not sure what the best solution is. Likely `ros-drivers/ros2_ouster_drivers` is better maintained, but the naming won't  match up given the `ouster_msgs` package name.

**Comment by jeychandar** [comment]
Hi I have tried as you said but still it is not showing the topic information. I could not understand what ros trying to say.I can't figure out this issue. Am i missing something. Rosbag info should run on rosbag_v2 but  why ROS 1 to ROS 2 type mapping is not available that I don't understand. It's been a week still am not getting answers from anywhere. When I tried to play this happens.

praveen@ubuntu:~$ ros2 bag play -s rosbag_v2 /home/praveen/catkin_ws/2023-01-24-18-18-10.bag
[INFO] [1674566894.245883932] [rosbag2_bag_v2_plugins]: ROS 1 to ROS 2 type mapping is not available for topic '/ouster/imu_packets' which is of type 'ouster_ros/PacketMsg'. Skipping messages of this topic when replaying.
[INFO] [1674566894.246065963] [rosbag2_bag_v2_plugins]: ROS 1 to ROS 2 type mapping is not available for topic '/ouster/lidar_packets' which is of type 'ouster_ros/PacketMsg'. Skipping messages of this topic when replaying.
[WARN] [1674566894.290635194] [rosbag2_cpp]: No topics were listed in metadata.

**Comment by emersonknapp** [comment]
Can you please attach/provide a sample bagfile to test against? I do not have an Ouster lidar and do not have much time for this issue, but if you make it easy I might be able to try.

> I have tried as you said

What exact code/commands did you write/run?

**Comment by jeychandar** [comment]
Hi. I have tried and got the topic information. The issue is related with record and topic name change. Resolved!!. Thanks for the help Sir :)
