### ISSUE TITLE
ros2 bag play error: 'cdr' does not exist

### ISSUE THREAD

**Issue by copaah** [ros2/rosbag2_bag_v2#9]
Trying to playback a bag file recorded with ROS 1. Following the readme in this repo and sourcing in the appropriate order in a new terminal:

```
source /opt/ros/melodic/setup.bash
source /opt/ros/dashing/setup.bash
```

Running 

```
ros2 bag info -s rosbag_v2 path/to/bag

Files:             my_bag
Bag size:          1.0 GiB
Storage id:        rosbag_v2
Duration:          25.636s
Start:             Oct 25 2018 11:13:23.864 (1540458803.864)
End                Oct 25 2018 11:13:49.500 (1540458829.500)
Messages:          2053
Topic information: Topic: /left_camera/camera_info | Type: sensor_msgs/msg/CameraInfo | Count: 513 | Serialization Format: rosbag_v2
                   Topic: /right_camera/camera_info | Type: sensor_msgs/msg/CameraInfo | Count: 514 | Serialization Format: rosbag_v2
                   Topic: /left_camera/image_raw_align | Type: sensor_msgs/msg/Image | Count: 513 | Serialization Format: rosbag_v2
                   Topic: /right_camera/image_raw_align | Type: sensor_msgs/msg/Image | Count: 513 | Serialization Format: rosbag_v2
```

Which seems to be working fine. However, if I try to play the bag

```
ros2 bag play -s rosbag_v2 path/to/bag
```
I get the following error: 

<pre><font color="#CC0000">[ERROR] [rosbag2]: Requested converter for format &apos;cdr&apos; does not exist</font>
<font color="#CC0000">[ERROR] [rosbag2_transport]: Failed to play: Could not find converter for format cdr</font>
</pre>

**Comment by Karsten1987** [comment]
I am not able to reproduce this locally on my computer.
But just for me to make sure I understand your commands correctly:

`path/to/bag` points to an actual `.bag` file or to a top-level folder which contains the bag file?

Also, can you make sure that you have all rosbag2 plugins installed? Namely this one: `ros-dashing-rosbag2-converter-default-plugins`

**Comment by copaah** [comment]
Installing that plugin solved it! I only had the following one installed:

```
sudo apt install -y ros-dashing-rosbag2-bag-v2-plugins
```

**Comment by jimaldon** [comment]
> ros-dashing-rosbag2-converter-default-plugins

I can't find this package anymore @Karsten1987 Has it been renamed?
